/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-04 08:29:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1727831655258L));
    _jspx_dependants.put("jar:file:/C:/KOSTA_LHJ/apache-tomcat-9.0.93/webapps/workshop05/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<title>도서 등록 - ENCORE</title>\r\n");
      out.write("	<META http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	function confirmation(){\r\n");
      out.write("		if(isbn1.value.length!=4){\r\n");
      out.write("			alert (\"도서번호1 길이를 잘못 입력하였습니다.\");\r\n");
      out.write("			isbn1.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(isbn2.value.length!=3){\r\n");
      out.write("			alert (\"도서번호2 길이를 잘못 입력하였습니다.\");\r\n");
      out.write("			isbn2.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("		if(isbn3.value.length!=3){\r\n");
      out.write("			alert (\"도서번호3 길이를 잘못 입력하였습니다.\");\r\n");
      out.write("			isbn3.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}		\r\n");
      out.write("		//도서종류 선택 확인	\r\n");
      out.write("		catalogue=document.getElementById(\"catalogue\");\r\n");
      out.write("		if(catalogue.value=='NONE'){\r\n");
      out.write("			alert(\"도서종류를 선택하십시요.\");\r\n");
      out.write("			catalogue.focus();\r\n");
      out.write("			return;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("		bookForm.submit();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	/*************************************************************************\r\n");
      out.write("    취소 버튼을 누르면 폼데이터 초기화\r\n");
      out.write("	**************************************************************************/\r\n");
      out.write("	function formReset() {\r\n");
      out.write("		bookForm.reset();\r\n");
      out.write("		bookForm.isbn1.focus();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("h4  {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".isbn {\r\n");
      out.write("	width: 50px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body >\r\n");
      out.write("\r\n");
      out.write("<!--도서등록 타이틀 테이블 시작//-->\r\n");
      out.write("<table width=\"650\" cellpadding=\"0\" cellspacing=\"0\"  align=\"center\" >\r\n");
      out.write("	<tr bgcolor=\"#E3E3E3\">\r\n");
      out.write("		<td width=\"700\"  valign=\"middle\" >\r\n");
      out.write("			<center><h2>도서 등록 화면</h2></center>\r\n");
      out.write("		</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("</table>\r\n");
      out.write("<!--도서등록 타이틀 끝//-->\r\n");
      out.write("\r\n");
      out.write("<p>\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!--도서정보입력 FORM 테이블시작//-->\r\n");
      out.write("<FORM METHOD=\"post\" action=\"bookRegister.do\" name=\"bookForm\" id=\"bookForm\">\r\n");
      out.write("\r\n");
      out.write("	<!--도서아이디정보 입력 테이블 시작//-->\r\n");
      out.write("	<Table cellpadding=\"0\" cellspacing=\"1\" border=\"0\" width=\"650\" bgcolor=\"#EAEAEA\" align=\"center\">\r\n");
      out.write("		<!-- 필수입력필드표기 -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"650\" bgcolor=\"#FFFFFF\" height=\"35\"  valign=\"middle\" align=\"right\" colspan=\"2\">\r\n");
      out.write("				<img src=\".\\image\\star_orange.gif\" hspace=\"7\" vspace=\"3\">표시가 된 항목은 필수 입력 항목입니다.\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td width=\"650\" bgcolor=\"#F3F3F3\" height=\"35\" colspan=\"2\">\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<!--도서번호 입력-->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\" valign=\"middle\">\r\n");
      out.write("				<img src=\".\\image\\star_orange.gif\" hspace=\"7\" vspace=\"3\">도서번호\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"number\" name=\"isbn1\"  id=\"isbn1\"  class=\"isbn\" MAXLENGTH=\"4\" required=\"required\"    tabindex=\"1\">-\r\n");
      out.write("				<input type=\"number\" name=\"isbn2\"  id=\"isbn2\"  class=\"isbn\"	MAXLENGTH=\"3\" required=\"required\"   tabindex=\"2\">-\r\n");
      out.write("				<input type=\"number\" name=\"isbn3\"  id=\"isbn3\"  class=\"isbn\" MAXLENGTH=\"3\" required=\"required\"   tabindex=\"3\">\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<!--도서제목-->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\" valign=\"middle\">\r\n");
      out.write("				<img src=\".\\image\\star_orange.gif\" hspace=\"7\" vspace=\"3\">도서제목\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"text\" name=\"title\"  id=\"title\" size=\"50\" MAXLENGTH=\"50\" tabindex=\"4\" required=\"required\" >&nbsp;\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<!--도서종류-->\r\n");
      out.write("	    <tr>    \r\n");
      out.write("          <td  bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\" valign=\"middle\">  \r\n");
      out.write("			<img src=\".\\image\\star_orange.gif\" hspace=\"7\" vspace=\"3\" >도서종류\r\n");
      out.write("		  </td>  \r\n");
      out.write("          <td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;  \r\n");
      out.write("				<select NAME=\"catalogue\" id=\"catalogue\" tabindex=\"5\">\r\n");
      out.write("				<option value=\"NONE\">해당 항목을 선택하세요</option>\r\n");
      out.write("				<option value=\"프로그래밍\">프로그래밍</option>\r\n");
      out.write("				<option value=\"운영체제\">운영체제</option>\r\n");
      out.write("				<option value=\"데이터베이스\">데이터베이스</option>\r\n");
      out.write("				<option value=\"네트워크\">네트워크</option>\r\n");
      out.write("				</select>\r\n");
      out.write("		   </td>\r\n");
      out.write("        </tr>   \r\n");
      out.write("		<!--출판국가-->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\">\r\n");
      out.write("				<img src=\".\\image\\square_gray.gif\" hspace=\"7\" vspace=\"3\">&nbsp;출판국가\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("				<input type=\"radio\" name=\"nation\" value=\"국내\" checked   tabindex=\"6\">국내도서\r\n");
      out.write("				<input type=\"radio\" name=\"nation\" value=\"외국\">외국도서\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<!--출판일-->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\">\r\n");
      out.write("				<img src=\".\\image\\square_gray.gif\" hspace=\"7\" vspace=\"3\">&nbsp;출&nbsp;판&nbsp;일\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("					<input type='text' name='publishDate' id=\"publishDate\" size='15'   tabindex=\"7\"> \r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<!--출판사 -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\">\r\n");
      out.write("				<img src=\".\\image\\square_gray.gif\" hspace=\"7\" vspace=\"3\">&nbsp;출&nbsp;판&nbsp;사\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("			<SELECT name='publisher' id=\"publisher\" tabindex=\"10\">\r\n");
      out.write("						<option value=\"NONE\">해당 항목을 선택하세요</option>\r\n");
      out.write("						<option value='영진출판사'>영진출판사</option>\r\n");
      out.write("						<option value='한빛미디어'>한빛미디어</option>\r\n");
      out.write("						<option value='자앤미디어'>자앤미디어</option>\r\n");
      out.write("						<option value='멀티캠퍼스'>멀티캠퍼스</option>\r\n");
      out.write("			</SELECT>\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("		<!-- 저자 -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\" valign=\"middle\">\r\n");
      out.write("				<img src=\".\\image\\star_orange.gif\" hspace=\"7\" vspace=\"3\">저&nbsp;&nbsp;&nbsp;&nbsp;자\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"text\" name=\"author\" id=\"author\" size=\"10\" MAXLENGTH=\"50\" tabindex=\"11\">&nbsp;\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("\r\n");
      out.write("		<!-- 도서가격 -->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\" width=\"120\" valign=\"middle\">\r\n");
      out.write("				<img src=\"./image\\square_gray.gif\" hspace=\"7\" vspace=\"3\">&nbsp;도서가격\r\n");
      out.write("			</td>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"35\">&nbsp;&nbsp;\r\n");
      out.write("					<input type=\"number\" name=\"price\" id=\"price\" size=\"10\" MAXLENGTH=\"6\" tabindex=\"12\">&nbsp;\r\n");
      out.write("				<select name=\"currency\" id=\"currency\" tabindex=\"13\">\r\n");
      out.write("					<option value=\"원\" selected>원</option>\r\n");
      out.write("					<option value=\"달러\">달러</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("	\r\n");
      out.write("		<!--요약내용-->\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td bgcolor=\"#FFFFFF\" height=\"60\" width=\"120\">\r\n");
      out.write("				<img src=\".\\image\\square_gray.gif\" hspace=\"7\" vspace=\"3\">&nbsp;요약내용\r\n");
      out.write("			</td>\r\n");
      out.write("			<td>&nbsp;&nbsp;\r\n");
      out.write("				<TEXTAREA NAME=\"description\" id=\"description\" ROWS=\"3\" COLS=\"50\" tabindex=\"14\"></TEXTAREA>\r\n");
      out.write("			</td>			\r\n");
      out.write("		</tr>	\r\n");
      out.write("	</table>\r\n");
      out.write("	<!--기본입력 테이블 끝//-->\r\n");
      out.write("\r\n");
      out.write("	<br>\r\n");
      out.write("	<Table cellpadding=\"0\" cellspacing=\"1\" border=\"0\" width=\"650\" bgcolor=\"#EAEAEA\" align=\"center\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td align=\"center\" height=\"30\" valign=\"middle\">\r\n");
      out.write("				<a href=\"javascript:confirmation()\"><img src=\".\\image\\ok.gif\" width=\"64\" height=\"29\" vspace=\"12\" hspace=\"2\" alt=\"확인\"  border=\"0\"  border=\"0\"></a>\r\n");
      out.write("				<a href=\"javascript:formReset()\"><img src=\".\\image\\cancel.gif\" width=\"64\" height=\"29\" vspace=\"12\" hspace=\"2\" alt=\"취소\"  border=\"0\" ></a>\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("</FORM>\r\n");
      out.write("<!--정보입력 테이블끝//-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<CENTER>\r\n");
      out.write("<FONT COLOR=\"NAVY\" SIZE=\"2\" FACE=\"굴림체\">\r\n");
      out.write("사전 도움말 - 이용약관 - 개인정보취급방침 - 책임의 한계와 법적고지 - 고객센터<BR> \r\n");
      out.write("Copyright ⓒ 2021 HABAREE. All Rights Reserved.\r\n");
      out.write("</FONT>\r\n");
      out.write("</CENTER>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /bookForm.jsp(70,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty user }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<h4>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님 로그인 되었습니다. <a href=\"memberLogout.do\">로그아웃</a></h4>\r\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
