-- 1.  MY_DEPT의 구조와 같은 테이블을 생성하는 SQL 구문을 작성하세요
CREATE TABLE MY_DEPT(
	DEPT_NO TINYINT,
	DEPT_NAME varchar(10),
	DEPT_LOC varchar(20),
	DEPT_TELNO varchar(15));
	
DESC MY_DEPT;

    
-- 2. MY_DEPT 테이블의 PK를 설정하는 구문을 추가하여 작성하세요. (단, PK 명은 MY_DEPT_PK ) 
ALTER TABLE MY_DEPT ADD CONSTRAINT MY_DEPT_DEPT_NO_PK PRIMARY KEY(DEPT_NO);

DESC MY_DEPT; 

-- 3. MY_DEPT 테이블에 위 표의 제공된 데이터를 입력하는 SQL 구문을 작성하세요.
INSERT INTO MY_DEPT(DEPT_NO, DEPT_NAME, DEPT_LOC, DEPT_TELNO) VALUES(10, 'SALES', 'SEOUL', '02-671-1111');
INSERT INTO MY_DEPT(DEPT_NO, DEPT_NAME, DEPT_LOC, DEPT_TELNO) VALUES(20, 'FINANCE', 'SEOUL', '02-862-2222');
INSERT INTO MY_DEPT(DEPT_NO, DEPT_NAME, DEPT_LOC, DEPT_TELNO) VALUES(30, 'HR', 'BUSAN', '051-111-1111');
INSERT INTO MY_DEPT(DEPT_NO, DEPT_NAME, DEPT_LOC, DEPT_TELNO) VALUES(40, 'PURCHASE', 'BUSAN', '051-222-2222');
INSERT INTO MY_DEPT(DEPT_NO, DEPT_NAME, DEPT_LOC, DEPT_TELNO) VALUES(50, 'MANAGEMENT', 'BUSAN', '02-383-3333');


-- 4. MY_EMP 직원 테이블 생성
CREATE TABLE MY_EMP(
	EMP_NO SMALLINT,
    EMP_NAME VARCHAR(10),
    EMP_MGR SMALLINT,
    HIREDATE DATE,
    SAL SMALLINT,
    DEPT_NO TINYINT);
	
DESC MY_EMP;

-- 5 MY_EMP의 PK, FK 추가하는 구문 작성
ALTER TABLE MY_EMP ADD CONSTRAINT MY_EMP_EMP_NO_PK PRIMARY KEY(EMP_NO);

ALTER TABLE MY_EMP ADD CONSTRAINT MY_EMP_DEPT_NO_FK FOREIGN KEY(DEPT_NO)
REFERENCES MY_DEPT(DEPT_NO)
ON DELETE CASCADE;

-- 6. MY_EMP 테이블에 제공된 데이터를 입력
INSERT INTO MY_EMP (EMP_NO, EMP_NAME, EMP_MGR, HIREDATE, SAL, DEPT_NO) VALUE (1001, 'KIM', 1003, '2019-01-15', 4750, 20);
INSERT INTO MY_EMP (EMP_NO, EMP_NAME, EMP_MGR, HIREDATE, SAL, DEPT_NO) VALUE (1002, 'LEE', 1003, '2021-06-05', 3000, 30);
INSERT INTO MY_EMP (EMP_NO, EMP_NAME, EMP_MGR, HIREDATE, SAL, DEPT_NO) VALUE (1003, 'PARK', 1001, '2023-11-28', 3500, 10);
SELECT * FROM MY_EMP;

SELECT * FROM MY_EMP;  

-- 7. MY_EMP 테이블에 ‘HR’ 부서 직원의  소속 부서를 ‘MANAGEMENT’ 부서로 변경하는 SQL 구문을 작성하세요.

UPDATE MY_EMP
SET DEPT_NO=(SELECT DEPT_NO FROM MY_DEPT WHERE DEPT_NAME='MANAGEMENT')
WHERE DEPT_NO=(SELECT DEPT_NO FROM MY_DEPT WHERE DEPT_NAME='HR');

SELECT * FROM MY_EMP;

-- 8. MY_DEPT 테이블에 ‘HR’ 부서를 삭제하는 SQL 구문을 작성하세요.
DELETE FROM MY_DEPT WHERE DEPT_NAME='HR';
 

-- 9. 데이터 추가, 현재 날짜 함수 사용 : sysdate
INSERT INTO MY_EMP(EMP_NO, EMP_NAME, EMP_MGR, HIREDATE, SAL, DEPT_NO) 
VALUES(2001, 'chung', 1001, curdate(), 3000, 50);


-- 10. MY_EMP, MY_DEPT 테이블을 부서코드로 JOIN해서 VIEW 생성
CREATE VIEW EMP_DEPT_VIEW 
AS
(SELECT e.EMP_NO, e.EMP_NAME, e.EMP_MGR, e.HIREDATE, e.SAL, d.DEPT_NO, d.DEPT_NAME, d.DEPT_LOC
FROM MY_EMP e JOIN MY_DEPT d ON e.DEPT_NO = d.DEPT_NO);


-- 11. 생성된 VIEW 실행
SELECT * FROM EMP_DEPT_VIEW;


-- 12. MY_EMP 테이블 EMP_NAME에 중복 허용 인덱스를 걸자. 
CREATE INDEX my_emp_emp_name_idx ON MY_EMP(EMP_NAME);

SELECT * FROM MY_DEPT;
SELECT * FROM MY_EMP;
SHOW INDEX FROM MY_EMP;



    