#!/bin/sh
# ---------------------------------------------------------------------------
# tc Server Script
#
# Copyright (c) 2017-2018 Pivotal Software, Inc.  All rights reserved.
# ---------------------------------------------------------------------------
# version: 4.0.4.RELEASE
# build date: 20181128221035

# Utility function for echoing to stderr
echoerr() {
   echo "$@" 1>&2
}

SCRIPT="$0"

# SCRIPT may be an arbitrarily deep series of symlinks. Loop until we have the concrete path.
while [ -h "$SCRIPT" ] ; do
  ls=`ls -ld "$SCRIPT"`
  # Drop everything prior to ->
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    SCRIPT="$link"
  else
    SCRIPT=`dirname "$SCRIPT"`/"$link"
  fi
done

# Test for the existence of JAVA_HOME env variable and exit if not set
if [ -z "$JAVA_HOME" ]; then
  if [ "$darwin" = "true" ]; then
    # Bugzilla 54390
    if [ -x '/usr/libexec/java_home' ] ; then
      export JAVA_HOME=`/usr/libexec/java_home`
    # Bugzilla 37284 (reviewed).
    elif [ -d "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home" ]; then
      export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Home"
    fi
  else
    JAVA_PATH=`which java 2>/dev/null`
    if [ ! -z "$JAVA_PATH" ]; then
      JAVA_PATH=`dirname $JAVA_PATH 2>/dev/null`
      JAVA_HOME=`dirname $JAVA_PATH 2>/dev/null` #Remove the 'bin' from the path
    fi
    if [ -z "$JAVA_HOME" ]; then
      # XXX: Should we try other locations?
      if [ -x /usr/bin/java ]; then
        JAVA_HOME=/usr
      fi
    fi
  fi
  if [ -z "$JAVA_HOME" ]; then
    echo "The JAVA_HOME environment variable is not defined"
    echo "This environment variable is needed to run this program"
    exit 1
  fi
fi


if [ ! -x "$JAVA_HOME/bin/java" ]; then
  echoerr "$JAVA_HOME/bin/java is not executable"
  exit 1
fi

INSTALLATION_DIR=`dirname "$SCRIPT"`
CONF_DIR=$INSTALLATION_DIR/conf

PARENT_DIR=$INSTALLATION_DIR/../

RUNTIME_DIR=$PARENT_DIR/runtimes
INSTANCE_DIR=$PARENT_DIR/instances

CLASSPATH=""

LIB_DIR=`dirname "$SCRIPT"`/lib
for file in "$LIB_DIR"/*.jar
do
  if [ -n "$CLASSPATH" ]
  then	
    CLASSPATH=$CLASSPATH:$file
  else
    CLASSPATH=$file
  fi
done

if [ -z "$COLUMNS" ]; then
  if [ ! -z "$TERM" ]; then
    if command -v tput >/dev/null 2>&1; then
      COLUMNS=`tput cols`
    fi
  fi
fi

JAVA_HOME="$JAVA_HOME" "$JAVA_HOME/bin/java" "-Djava.util.logging.config.file=$CONF_DIR/commons-logging.properties" -Dtcs.terminal.columns="$COLUMNS" $JAVA_OPTS "-Dinstallation.directory=$INSTALLATION_DIR" "-Druntimes.directory=$RUNTIME_DIR" "-Ddefault.instances.directory=$INSTANCE_DIR" -classpath "$CLASSPATH" com.springsource.tcruntime.instance.TcServer "$@"
EXIT_CODE=$?

exit $EXIT_CODE
